layouts:
    - tall
    - widescreen-tall
    - fullscreen
    - wide
    - two-pane
    - 3column-left
    - 3column-right
mod1:
    - control
    - shift
mod2:
    - control
    - shift
    - option
# Modify the amethyst relaunch to use x and not z
relaunch-amethyst:
    mod: mod2
    key: x

# Enable focus-follows-mouse
mouse-follows-focus: false
focus-follows-mouse: true

# Add 10px margin between windows
window-margins: true
window-margin-size: 10
