# Ansi color code
# https://i.stack.imgur.com/KTSQa.png

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$fill
$hostname\
$username\
$directory\
$git_branch\
$python\
$conda\
$golang\
$cmd_duration
$character
"""

[hostname]
ssh_only = true
format = '[$ssh_symbol](fg:14) '

[username]
# style_user = 'fg:250'
format = '\[[$user]($style):'
show_always = true

[character]
success_symbol = "[➜](fg:10) "
error_symbol = "[✗](fg:1) "

[directory]
format = '[$path]($style)[$read_only]($read_only_style)\] '
truncation_length = 100
truncate_to_repo = false

[git_branch]
format='\[[git:$branch(:$remote_branch)]($style)\] '
style = "fg:13"

[fill]
symbol="─"
style = 'fg:240'

[cmd_duration]
min_time = 0
show_milliseconds = true
style = 'fg:240'
format = "[$duration]($style)"

[time]
disabled = true

[package]
disabled = true

[python]
format = '\[[py ${pyenv_prefix}(${version})(\($virtualenv\))]($style)\] '

[conda]
format = '\[[conda $environment]($style)\] '

[golang]
format = '\[[golang:($version)]($style)\]'
detect_files = ["go.mod"]